local i = require("luasnip.nodes.insertNode").I
local jinja_filter_snippets = require("snippets.jinja_utils").jinja_filter_snippets

-- Jinja tests
return jinja_filter_snippets({
  boolean = { nodes = false },
  callable = { nodes = false },
  defined = { nodes = false },
  divisibleby = { nodes = i(1, "num") },
  eq = { nodes = true },
  equalto = { nodes = true },
  escaped = { nodes = false },
  even = { nodes = false },
  ["false"] = { nodes = false },
  filter = { nodes = false },
  float = { nodes = false },
  ge = { nodes = true },
  gt = { nodes = true },
  greaterthan = { nodes = true },
  ["in"] = { nodes = true },
  integer = { nodes = false },
  iterable = { nodes = false },
  le = { nodes = true },
  lower = { nodes = false },
  lt = { nodes = true },
  lessthan = { nodes = true },
  mapping = { nodes = false },
  ne = { nodes = false },
  none = { nodes = false },
  number = { nodes = false },
  odd = { nodes = false },
  sameas = { nodes = true },
  sequence = { nodes = false },
  string = { nodes = false },
  test = { nodes = false },
  ["true"] = { nodes = false },
  undefined = { nodes = false },
  upper = { nodes = false },
})
