# vim: ft=yaml.ansible

- name: Dotfiles installation
  hosts: localhost
  connection: local
  vars_prompt:
    - name: force
      prompt: >
        Overwrite your configs if any (yes/no)?
        If `yes`, the following configs will be removed: nvim, fish, tmux, git.
      private: false
      default: "false"

  tasks:
    - name: Getting facts about target files and directories
      ansible.builtin.stat:
        path: "{{ item }}"
      register: path_facts
      loop:
        - ~/.config/nvim
        - ~/.config/fish
        - ~/.config/tmux
        - ~/.config/git
        - ~/.config/bat

    - name: Removing any existing files and directories
      ansible.builtin.file:
        path: "{{ item.item }}"
        state: absent
      when:
        - force | bool
        - item.stat.exists
        - item.stat.isdir or item.stat.isreg
      loop: "{{ path_facts.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Making symlink for neovim configuration
      ansible.builtin.file:
        path: ~/.config/nvim
        src: "{{ playbook_dir }}/nvim"
        state: link

    - name: Making symlink for fish configuration
      ansible.builtin.file:
        path: ~/.config/fish
        src: "{{ playbook_dir }}/fish"
        state: link

    - name: Making symlink for tmux configuration
      ansible.builtin.file:
        path: ~/.config/tmux
        src: "{{ playbook_dir }}/tmux"
        force: "{{ force | bool }}"
        state: link

    - name: Making symlink for git configuration
      ansible.builtin.file:
        path: ~/.config/git
        src: "{{ playbook_dir }}/git"
        state: link

    - name: Making symlink for bat configuration
      ansible.builtin.file:
        path: ~/.config/bat
        src: "{{ playbook_dir }}/bat"
        state: link
      notify: Building bat cache

    - name: Removing obsolete directory for vim plugins from nix
      ansible.builtin.file:
        path: ~/.local/share/nvim/site/pack/nix
        state: absent

    - name: Removing obsolete files from packer.nvim
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - ~/.local/share/nvim/site/pack/packer
        - ~/.local/share/nvim/site/plugin/packer_compiled.lua

    - name: Removing obsolete tmux.conf file
      ansible.builtin.file:
        path: ~/.tmux.conf
        state: absent

  handlers:
    - name: Building bat cache
      ansible.builtin.command:
        cmd: bat cache --build
