# GENERATED by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{ lib, buildVimPlugin, buildNeovimPlugin, fetchFromGitHub, fetchgit }:

final: prev:
{
  mediawiki-vim = buildVimPlugin {
    pname = "mediawiki.vim";
    version = "2015-11-15";
    src = fetchFromGitHub {
      owner = "chikamichi";
      repo = "mediawiki.vim";
      rev = "26e5737264354be41cb11d16d48132779795e168";
      sha256 = "1laiiww2lhn0v1039n0mx97fyyj7wdzwi0ybwl1ysdik03nxl32f";
    };
    meta.homepage = "https://github.com/chikamichi/mediawiki.vim/";
  };

  surround-nvim = buildVimPlugin {
    pname = "surround.nvim";
    version = "2022-02-01";
    src = fetchFromGitHub {
      owner = "ur4ltz";
      repo = "surround.nvim";
      rev = "549045828bbd9de0746b411a762fa8c382fb10ff";
      sha256 = "0dw10lk7vd2axdd8kf532x9q5hrj6b8qcazni456qy2vrbipyx2x";
    };
    meta.homepage = "https://github.com/ur4ltz/surround.nvim/";
  };

  vim-jinja2-syntax = buildVimPlugin {
    pname = "vim-jinja2-syntax";
    version = "2021-06-22";
    src = fetchFromGitHub {
      owner = "Glench";
      repo = "Vim-Jinja2-Syntax";
      rev = "2c17843b074b06a835f88587e1023ceff7e2c7d1";
      sha256 = "13mfzsw3kr3r826wkpd3jhh1sy2j10hlj1bv8n8r01hpbngikfg7";
    };
    meta.homepage = "https://github.com/Glench/Vim-Jinja2-Syntax/";
  };


}
