# This file has been generated by ./pkgs/applications/editors/vim/plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, buildNeovimPluginFrom2Nix, fetchFromGitHub, fetchgit }:

final: prev:
{
  mediawiki-vim = buildVimPluginFrom2Nix {
    pname = "mediawiki.vim";
    version = "2015-11-15";
    src = fetchFromGitHub {
      owner = "chikamichi";
      repo = "mediawiki.vim";
      rev = "26e5737264354be41cb11d16d48132779795e168";
      sha256 = "1laiiww2lhn0v1039n0mx97fyyj7wdzwi0ybwl1ysdik03nxl32f";
    };
    meta.homepage = "https://github.com/chikamichi/mediawiki.vim/";
  };

  surround-nvim = buildVimPluginFrom2Nix {
    pname = "surround.nvim";
    version = "2022-02-01";
    src = fetchFromGitHub {
      owner = "ur4ltz";
      repo = "surround.nvim";
      rev = "549045828bbd9de0746b411a762fa8c382fb10ff";
      sha256 = "0dw10lk7vd2axdd8kf532x9q5hrj6b8qcazni456qy2vrbipyx2x";
    };
    meta.homepage = "https://github.com/ur4ltz/surround.nvim/";
  };

  tmux-nvim = buildVimPluginFrom2Nix {
    pname = "tmux.nvim";
    version = "2023-01-18";
    src = fetchFromGitHub {
      owner = "aserowy";
      repo = "tmux.nvim";
      rev = "4e746b3707d4e499acc50d4e64c2fc4f0faf9a44";
      sha256 = "0ynjvf23hr9lyff08k9l80ipxvk7d4q0xjd6afnprvcans2k69pp";
    };
    meta.homepage = "https://github.com/aserowy/tmux.nvim/";
  };

  vim-fish-syntax = buildVimPluginFrom2Nix {
    pname = "vim-fish-syntax";
    version = "2022-08-05";
    src = fetchFromGitHub {
      owner = "khaveesh";
      repo = "vim-fish-syntax";
      rev = "f3744201a10addee5f1bf43146b611c39a1a5e4e";
      sha256 = "0bf0523pgqpp91pbp7k541c8m7dc2hv0iirv339g7d4v90i78wbd";
    };
    meta.homepage = "https://github.com/khaveesh/vim-fish-syntax/";
  };

  vim-jinja2-syntax = buildVimPluginFrom2Nix {
    pname = "vim-jinja2-syntax";
    version = "2021-06-22";
    src = fetchFromGitHub {
      owner = "Glench";
      repo = "Vim-Jinja2-Syntax";
      rev = "2c17843b074b06a835f88587e1023ceff7e2c7d1";
      sha256 = "13mfzsw3kr3r826wkpd3jhh1sy2j10hlj1bv8n8r01hpbngikfg7";
    };
    meta.homepage = "https://github.com/Glench/Vim-Jinja2-Syntax/";
  };


}
