# PC spec:
#
# CPU: Intel i7-6700K (4,4 GHz)
# RAM: 32GB DDR4 (3000 MHz)
# GPU: NVIDIA GeForce GTX 1080 Ti (11 GB VRAM, PCIe 3.0 x16)
#

[*]
#lv = 4

[qwen3.6-35b-a3b]
model = c:\models\unsloth\Qwen3.5-35B-A3B-MTP-GGUF\Qwen3.5-35B-A3B-UD-Q4_K_M.gguf
ctx-size = 92160
mmproj = c:\models\unsloth\Qwen3.5-35B-A3B-MTP-GGUF\mmproj-F16.gguf
mmproj-offload = off
spec-type = draft-mtp
spec-draft-n-max = 2
fit = off
n-cpu-moe = 31

[qwen3.6-35b-a3b:vision]
model = c:\models\unsloth\Qwen3.5-35B-A3B-MTP-GGUF\Qwen3.5-35B-A3B-UD-Q4_K_M.gguf
ctx-size = 51200
mmproj = c:\models\unsloth\Qwen3.5-35B-A3B-MTP-GGUF\mmproj-F16.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
fit = off
n-cpu-moe = 31

[qwen3.6-35b-a3b:context]
model = c:\models\unsloth\Qwen3.5-35B-A3B-MTP-GGUF\Qwen3.5-35B-A3B-UD-Q4_K_M.gguf
ctx-size = 204800
mmproj = c:\models\unsloth\Qwen3.5-35B-A3B-MTP-GGUF\mmproj-F16.gguf
mmproj-offload = off
fit = off
n-cpu-moe = 33
cache-ram = 2048

[tiel-coder-35b-a3b]
model = c:\models\peculiar-ragdoll\Tiel-Coder-35B-A3B-GGUF-MTP\Tiel-Coder-35B-A3B-MTP-UD-Q4_K_XL.gguf
ctx-size = 81920
mmproj = c:\models\peculiar-ragdoll\Tiel-Coder-35B-A3B-GGUF-MTP\mmproj-BF16.gguf
mmproj-offload = off
spec-type = draft-mtp
spec-draft-n-max = 2
fit = off
n-cpu-moe = 31

[tiel-coder-35b-a3b:vision]
model = c:\models\peculiar-ragdoll\Tiel-Coder-35B-A3B-GGUF-MTP\Tiel-Coder-35B-A3B-MTP-UD-Q4_K_XL.gguf
ctx-size = 35840
mmproj = c:\models\peculiar-ragdoll\Tiel-Coder-35B-A3B-GGUF-MTP\mmproj-BF16.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
fit = off
n-cpu-moe = 31

[tiel-coder-35b-a3b:context]
model = c:\models\peculiar-ragdoll\Tiel-Coder-35B-A3B-GGUF-MTP\Tiel-Coder-35B-A3B-MTP-UD-Q4_K_XL.gguf
ctx-size = 204800
mmproj = c:\models\peculiar-ragdoll\Tiel-Coder-35B-A3B-GGUF-MTP\mmproj-BF16.gguf
mmproj-offload = off
fit = off
n-cpu-moe = 33
cache-ram = 2048

[kat-coder-v2.5-dev]
model = c:\models\Myric\KAT-Coder-V2.5-Dev-MTP-APEX-GGUF\KAT-Coder-V2.5-Dev-MTP-APEX-i-quality-v2.gguf
ctx-size = 102400
chat-template-file = c:\Users\Stas\AppData\Roaming\llama.cpp\qwen3.6_unsloth.jinja
spec-type = draft-mtp
spec-draft-n-max = 2
fit = off
n-cpu-moe = 33

[kat-coder-v2.5-dev:context]
model = c:\models\Myric\KAT-Coder-V2.5-Dev-MTP-APEX-GGUF\KAT-Coder-V2.5-Dev-MTP-APEX-i-quality-v2.gguf
ctx-size = 215040
chat-template-file = c:\Users\Stas\AppData\Roaming\llama.cpp\qwen3.6_unsloth.jinja
fit = off
n-cpu-moe = 34

[gemma-4-26b-a4b]
model = c:\models\unsloth\gemma-4-26B-A4B-it-qat-GGUF\gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
ctx-size = 102400
mmproj = c:\models\unsloth\gemma-4-26B-A4B-it-qat-GGUF\mmproj-F16.gguf
mmproj-offload = off
spec-type = draft-mtp
spec-draft-model = c:\models\unsloth\gemma-4-26B-A4B-it-qat-GGUF\mtp-gemma-4-26B-A4B-it.gguf
spec-draft-n-max = 2
fit = off
n-cpu-moe = 20

[gemma-4-26b-a4b:vision]
model = c:\models\unsloth\gemma-4-26B-A4B-it-qat-GGUF\gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
ctx-size = 71680
mmproj = c:\models\unsloth\gemma-4-26B-A4B-it-qat-GGUF\mmproj-F16.gguf
spec-type = draft-mtp
spec-draft-model = c:\models\unsloth\gemma-4-26B-A4B-it-qat-GGUF\mtp-gemma-4-26B-A4B-it.gguf
spec-draft-n-max = 2
fit = off
n-cpu-moe = 21

[gemma-4-26b-a4b:context]
model = c:\models\unsloth\gemma-4-26B-A4B-it-qat-GGUF\gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
ctx-size = 194560
mmproj = c:\models\unsloth\gemma-4-26B-A4B-it-qat-GGUF\mmproj-F16.gguf
mmproj-offload = off
spec-type = draft-mtp
spec-draft-model = c:\models\unsloth\gemma-4-26B-A4B-it-qat-GGUF\mtp-gemma-4-26B-A4B-it.gguf
spec-draft-n-max = 2
fit = off
n-cpu-moe = 26

[gemma-4-12b]
model = c:\models\unsloth\gemma-4-12B-it-qat-GGUF\gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
ctx-size = 81920
mmproj = c:\models\unsloth\gemma-4-12B-it-qat-GGUF\mmproj-F16.gguf
mmproj-offload = off
spec-type = draft-mtp
spec-draft-model = c:\models\unsloth\gemma-4-12B-it-qat-GGUF\mtp-gemma-4-12B-it.gguf
spec-draft-n-max = 3
fit = off
cache-ram = 8192

[gemma-4-12b:vision]
model = c:\models\unsloth\gemma-4-12B-it-qat-GGUF\gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
ctx-size = 65536
mmproj = c:\models\unsloth\gemma-4-12B-it-qat-GGUF\mmproj-F16.gguf
spec-type = draft-mtp
spec-draft-model = c:\models\unsloth\gemma-4-12B-it-qat-GGUF\mtp-gemma-4-12B-it.gguf
spec-draft-n-max = 3
fit = off
cache-ram = 8192

[gemma-4-12b:context]
model = c:\models\unsloth\gemma-4-12B-it-qat-GGUF\gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
ctx-size = 158720
mmproj = c:\models\unsloth\gemma-4-12B-it-qat-GGUF\mmproj-F16.gguf
mmproj-offload = off
fit = off
cache-ram = 8192

[north-mini-code-1.0]
model = c:\models\unsloth\North-Mini-Code-1.0-GGUF\North-Mini-Code-1.0-UD-Q4_K_XL.gguf
ctx-size = 102400
fit = off
n-cpu-moe = 35

[north-mini-code-1.0:context]
model = c:\models\unsloth\North-Mini-Code-1.0-GGUF\North-Mini-Code-1.0-UD-Q4_K_XL.gguf
ctx-size = 174080
fit = off
n-cpu-moe = 39

[ornith-1.5-9b]
model = c:\models\ornith-ai\Ornith-1.5-9B-GGUF\Ornith-1.5-9B-Q5_K_M.gguf
ctx-size = 97280
mmproj = c:\models\ornith-ai\Ornith-1.5-9B-GGUF\mmproj-Ornith-1.5-9B-BF16.gguf
mmproj-offload = off
spec-type = draft-mtp
spec-draft-n-max = 2
fit = off
cache-ram = 8192

[ornith-1.5-9b:vision]
model = c:\models\ornith-ai\Ornith-1.5-9B-GGUF\Ornith-1.5-9B-Q5_K_M.gguf
ctx-size = 66560
mmproj = c:\models\ornith-ai\Ornith-1.5-9B-GGUF\mmproj-Ornith-1.5-9B-BF16.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
fit = off
cache-ram = 8192

[ornith-1.5-9b:context]
model = c:\models\ornith-ai\Ornith-1.5-9B-GGUF\Ornith-1.5-9B-Q4_K_M.gguf
ctx-size = 168960
mmproj = c:\models\ornith-ai\Ornith-1.5-9B-GGUF\mmproj-Ornith-1.5-9B-BF16.gguf
mmproj-offload = off
fit = off
cache-ram = 8192
